# Generated by Django 3.1 on 2020-11-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_auto_20201031_0816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Format',
        ),
        migrations.AlterField(
            model_name='post',
            name='postTitle',
            field=models.CharField(max_length=100),
        ),
    ]
